//CREAR TABLAS

CREATE TABLE PRODUCTOS(ID_PRODUCTO INTEGER, DESCRIPCION VARCHAR2(300), PIEZAS INTEGER); 
CREATE TABLE PROVEEDORES(ID_PROVEEDOR INTEGER, ID_PRODUCTO INTEGER, NOMBRE VARCHAR2(80), TELEFONO INTEGER, EMAIL VARCHAR2(50), DIRECCION VARCHAR2(200));
//secuencia y entrada a procedimiento
CREATE SEQUENCE SEC_PRODUCTO
     START WITH 1 
    INCREMENT BY 1 
     NOMAXVALUE; 
   /
   
   
SET SERVEROUTPUT ON;
DECLARE
VALOR INTEGER;

BEGIN 
 GUARDAR_PRODUCTO(VALOR,'MANCUERNA 30 CM',6,156.5); 
END; 
 / 



//crear procedimiento

CREATE OR REPLACE PROCEDURE GUARDAR_PRODUCTO
 ( 
   MY_ID_PRODUCTO OUT NUMBER   
 , MY_DESCRIPCION IN VARCHAR2   
 , MY_PIEZAS IN NUMBER     
 , MY_PRECIO IN FLOAT
 ) AS  
 BEGIN 
 
 SELECT SEC_PRODUCTO.NEXTVAL INTO MY_ID_PRODUCTO FROM DUAL; 
INSERT INTO PRODUCTOS VALUES(MY_ID_PRODUCTO, MY_DESCRIPCION, MY_PIEZAS, MY_PRECIO); 
   
 END GUARDAR_PRODUCTO;
