DECLARE

  CURSOR CUR_NOMYSUE IS SELECT * FROM EMPLEADO_VENTAS;
  CURSOR CUR_SUCS IS SELECT * FROM SUCURSAL;
  
  BEGIN
  
    FOR FILA IN CUR_NOMYSUE LOOP
     FOR FILA2 IN CUR_SUCS LOOP
    IF FILA.ID_CLIENTE = FILA2.ID_CLIENTE THEN
    
      DBMS_OUTPUT.PUT_LINE('NOMBRE  '|| FILA.NOMBRE_CLIENTE || 'SUELDO  ' || FILA2.NOMBRE);
         END IF;
         END LOOP;   
         END LOOP;
  END;
 /
 SELECT EMPLEADO_VENTAS.ID_CLIENTE, EMPLEADO_VENTAS.NOMBRE_CLIENTE, SUCURSAL.NOMBRE FROM EMPLEADO_VENTAS JOIN SUCURSAL  ON EMPLEADO_VENTAS.ID_CLIENTE=SUCURSAL.ID_CLIENTE;
