 DECLARE 

 CURSOR CUR_EMPLEADOSUCURSAL IS SELECT NOMBRE_CLIENTE, NOMBRE FROM EMPLEADO_VENTAS, SUCURSAL WHERE  EMPLEADO_VENTAS.ID_CLIENTE = SUCURSAL.ID_CLIENTE;
   

    BEGIN
   
       FOR FILA IN CUR_EMPLEADOSUCURSAL LOOP
   
        DBMS_OUTPUT.PUT_LINE('NOMBRE DEL EMPLEADO '||FILA.NOMBRE_CLIENTE|| ' NUMERO DE SUCURSAL  ' || FILA.NOMBRE);
         
         END LOOP;
         
 END;
 /
