CREATE TABLE TRABAJADOR(ID_TRABAJADOR INTEGER,
              NOMBRE VARCHAR2(120),
               TIEMPO_LABORANDO INTEGER,
                SUELDO_BASE FLOAT,
                 CONSTRAINT PK_ID_TRABAJADOR PRIMARY KEY(ID_TRABAJADOR)
                 );
                 

                             
      CREATE TABLE NOMINA(ID_NOMINA INTEGER,
                     ID_TRABAJADOR INTEGER,
                      HORAS_LABORADAS INTEGER,
                       SALDO FLOAT,
                       CONSTRAINT PK_ID_NOMINA PRIMARY KEY(ID_NOMINA),
                         CONSTRAINT FK1_ID_TRABAJADOR FOREIGN KEY(ID_TRABAJADOR) REFERENCES TRABAJADOR(ID_TRABAJADOR)
      );
      
SET SERVEROUTPUT ON;

INSERT INTO TRABAJADOR VALUES(1,'GABRIELA',8,10000);
INSERT INTO NOMINA(ID_NOMINA,ID_TRABAJADOR) VALUES(1,1);

SELECT * FROM TRABAJADOR;

DESCRIBE NOMINA;
