create or replace 
PROCEDURE HOLA_MUNDO(NOMBRE IN VARCHAR2)
     AS 
     -- AQUI SE PONDRIAN LAS VARIABLES LOCALES
     BEGIN
     -- AQUI VA LA LOGICA DE PROGRAMACION
     
     DBMS_OUTPUT.PUT_LINE('HOLA COMO ESTAS ' || NOMBRE);
     
     END;
     
