--crearemos una tabla simple para probar el poder de sql  

CREATE TABLE DANCE(ID_DANCE INTEGER, NOMBRE VARCHAR2(40), EDAD INTEGER); 
--PRENDEMOS EL SERVIDOR EN MODO DESARROLLADOR

SET SERVEROUTPUT ON;
--VAMOS A EMPEZAR CON UN BLOQUE PL/SQL
DECLARE 
--AQUI SE DECLARAN LAS VARIABLES A USARSE
EDAD INTEGER;
YEARS INTEGER;

BEGIN 
--AQUI VA LA LOGICA DEL PROGRAMA
YEARS:=26;
MONTHS:=12;

EDAD:=YEARS*365;

DBMS_OUTPUT.PUT_LINE('TU EDAD EN DIAS ES '|| EDAD);

END;
/
