--crearemos una tabla simple para probar el poder de sql  

CREATE TABLE DANCE(ID_DANCE INTEGER, NOMBRE VARCHAR2(40), EDAD INTEGER); 
--PRENDEMOS EL SERVIDOR EN MODO DESARROLLADOR

SET SERVEROUTPUT ON;
--VAMOS A EMPEZAR CON UN BLOQUE PL/SQL
DECLARE 
--AQUI SE DECLARAN LAS VARIABLES A USARSE
EDAD INTEGER;
YEARS INTEGER;

BEGIN 
--AQUI VA LA LOGICA DEL PROGRAMA
YEARS:=26;
MONTHS:=12;

EDAD:=YEARS*365;

DBMS_OUTPUT.PUT_LINE('TU EDAD EN DIAS ES '|| EDAD);

END;
/

--CREAR UN BLOQUE PL SQL QUE GENERE 200.000 REGISTROS DE SECUENCIA EN LA TABLA DANCE

BEGIN

FOR I IN 1..200000 LOOP
 INSERT INTO DANCE VALUES(I,'NESTOR',26);
 
  END LOOP;
  END;
/


--VAMOS A VER QUE HICIMOS

SELECT * FROM DANCE;

-- SISTEMA DE PELICULAS

CREATE TABLE PELICULA(ID_PELICULA INTEGER,
              TITULO VARCHAR2(120),
               SINOPSIS VARCHAR2(500),
                CLASIFICACION VARCHAR2(5), CONSTRAINT PK_ID_PELICULA PRIMARY KEY(ID_PELICULA)
                 );
                 
DESCRIBE PELICULA;

                             
      CREATE TABLE HORARIO(ID_HORARIO INTEGER,
                     ID_PELICULA INTEGER,
                      HORARIO VARCHAR2(200),
                       CONSTRAINT PK_ID_HORARIO PRIMARY KEY(ID_HORARIO),
                         CONSTRAI
                         NT FK1_ID_PELICULA FOREIGN KEY(ID_PELICULA) REFERENCES PELICULA(ID_PELICULA)
      );
      
      
       CREATE TABLE SALA(ID_SALA INTEGER,
                     ID_PELICULA INTEGER,
                      NUM_SALA INTEGER,
                       CONSTRAINT PK_ID_SALA PRIMARY KEY(ID_SALA),
                         CONSTRAINT FK2_ID_PELICULA FOREIGN KEY(ID_PELICULA) REFERENCES PELICULA(ID_PELICULA)
      );


CREATE SEQUENCE sec_pelicula
  START WITH 1
   INCREMENT BY 3
    NOMAXVALUE;
     /

--el siguiente paso es ejecutar la recien creada secuencia con la tabla pelicula

-- NOTA_. SOLAMENTE SE PUEDE ASOCIAR UNA SECUENCIA CON UNA TABLA

---- PARA ASOCIARLA SE NECESITA UN NUEVO OBJETO DE BASE DE DATOS, ESTE OBJETO VA A SER EL QUE INSERTARA EL O LOS NUEVOS REGISTROS EN LA TABLA PELICULA
--EN RESUMEN

----- JAMAS SE USA UN INSERT INTO EN ORACLE CUANDO TIENEN UN PRIMARY KEY AUTO INCREMENTABLE



