CREATE OR REPLACE PROCEDURE ACTUALIZAR_PRODUCTO 
(
  MYID_PRODUCTO IN NUMBER  
, MY_NEWPRECIO IN FLOAT  
) AS 
BEGIN
   UPDATE PRODUCTO SET PRECIO = MY_NEWPRECIO WHERE ID_PRODUCTO = MYID_PRODUCTO;

END ACTUALIZAR_PRODUCTO;
