CREATE OR REPLACE PROCEDURE GUARDARLIBROS 
(
  MY_LIBROID OUT VARCHAR2  
, MY_ISBN IN VARCHAR2  
, MY_TITULO IN VARCHAR2  
, MY_RESUMEN IN VARCHAR2  
, MY_AUTOR IN VARCHAR2  
, DIA IN INTEGER
, MES IN VARCHAR2
, ANIO IN INTEGER
, MY_PAGINAS IN NUMBER

)
 
AS 
MY_DATE DATE;
   
BEGIN

MY_DATE:=to_date(''||DIA||'-'||MES||'-'||ANIO);

    SELECT SEC_LIBROS.NEXTVAL INTO MY_LIBROID FROM DUAL;
      INSERT INTO LIBROS VALUES(MY_LIBROID, MY_ISBN, MY_TITULO, MY_RESUMEN, MY_AUTOR, MY_DATE , MY_PAGINAS );
END GUARDARLIBROS;
