CREATE OR REPLACE PROCEDURE ACTUALIZAR_PRODUCTO 
(
  MYID_PRODUCTO IN NUMBER  
, MY_NEWPRECIO IN FLOAT  
) AS 
BEGIN
   UPDATE PRODUCTO SET PRECIO = MY_NEWPRECIO WHERE ID_PRODUCTO = MYID_PRODUCTO;

END ACTUALIZAR_PRODUCTO;



---en el  system---

BEGIN

ACTUALIZAR_PRODUCTO(1,34.6);
END;
/


CREATE OR REPLACE TRIGGER ACTUALIZARPRECIO BEFORE INSERT ON PRODUCTO   FOR EACH ROW
BEGIN
IF :NEW.precio <= :old.precio  THEN
RAISE_APPLICATION_ERROR (-20001,'LO SIENTO PRECIO MENOR QUE ');
ELSE
INSERT INTO PRODUCTO VALUES (:NEW.ID_PRODUCTO, :NEW.DESCRIPCION, :NEW.MARCA, :NEW.CATEGORIA, :NEW.PRECIO );
END IF;
END;
/

INSERT INTO PRODUCTO VALUES(1,'GALLETAS MARIAS','GAMESA', 'CEREALES', 33.50 );
